# example config yaml file
train:
  dataset_name: cifar10
  dataset_path: './data'

hparam:
  optim_name: adam
  learning_rate: 0.001
  epoch_base: 100
  epoch_per_task: 60
  batch_size: 64

task_info:
  cls_total: 10
  cls_base: 6
  num_tasks: 4
  cls_per_task: 1
